---
collections:
  - name: git@github.com:companieshouse/ansible-collections.git#/ch_collections/base/
    version: 0.1.126
    type: git
  - name: git@github.com:companieshouse/ansible-collections.git#/ch_collections/heritage_services
    version: 0.1.69
    type: git
  - name: git@github.com:companieshouse/ansible-collections.git#/ch_collections/enterpriselinux6
    version: 0.1.126
    type: git
  - name: community.general
    version: 4.8.0
  - name: ansible.posix
    version: 1.5.4
  - name: companieshouse.security
    version: 1.0.21
